frequency: 50
sensor_timeout: 0.5
print_diagnostics: false #echo the /diagnostics_agg topic for details

pose0: "pose"
pose0_config: [true, true, true,
              true, true, true,
              false, false, false,
              false, false, false,
              false, false, false]
pose0_nodelay: true
#predict_to_current_time: true
transform_timeout: 0.02


world_frame: map
map_frame: map
base_link_frame: base_link
